#!/usr/bin/env bash
# install nginx on a web server and listening on port 80

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install -y nginx 
sudo chown -R ubuntu:ubuntu /var/www
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
