#!/usr/bin/env bash
# Create a script to install and configure HAproxy on your lb-01 server.
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

# Install and configure HAProxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

#edit config file
server_configuration=\
"
frontend jite-frontend
	bind *:80
	mode http
	default_backend jite-backend
backend jite-backend
	balance roundrobin
	server 151571-web-01 54.144.153.231:80 check
	server 151571-web-02 34.229.55.205:80 check
"
echo "$server_configuration" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
